// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:9359cb3f-e03e-4b28-8d9b-32b9629ba496',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '4655f7b64193456e9f476425ac558396',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'fe6d8cfb-1cdd-4679-9815-c7c0086a54a0',
    'aws_project_name': 'cbt-companion',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'cbtcompanion-mobilehub-53352411',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'cbtcompanion-userfiles-mobilehub-53352411',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_8IKu6FeB5',
    'aws_user_pools_web_client_id': '5vbmv5pnuoooik08pn4t19uota',
}

export default awsmobile;
